// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/athunlal/bookNowTrain-svc/pkg/api"
	"github.com/athunlal/bookNowTrain-svc/pkg/api/handler"
	"github.com/athunlal/bookNowTrain-svc/pkg/config"
	"github.com/athunlal/bookNowTrain-svc/pkg/db"
	"github.com/athunlal/bookNowTrain-svc/pkg/repository"
	"github.com/athunlal/bookNowTrain-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHttp, error) {
	database, err := db.ConnectDataBase(cfg)
	if err != nil {
		return nil, err
	}
	trainRepo := repository.NewTrainRepo(database)
	trainUseCase := usecase.NewTrainUseCase(trainRepo)
	trainHandler := handler.NewTrainHandler(trainUseCase)
	serverHttp := api.NewServerHttp(trainHandler)
	return serverHttp, nil
}
