// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: pkg/pb/train.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Add route
type RouteStation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stationid int64                `protobuf:"varint,1,opt,name=stationid,proto3" json:"stationid,omitempty"`
	Distance  float32              `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Time      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *RouteStation) Reset() {
	*x = RouteStation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteStation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStation) ProtoMessage() {}

func (x *RouteStation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStation.ProtoReflect.Descriptor instead.
func (*RouteStation) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{0}
}

func (x *RouteStation) GetStationid() int64 {
	if x != nil {
		return x.Stationid
	}
	return 0
}

func (x *RouteStation) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RouteStation) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routeid  int64           `protobuf:"varint,1,opt,name=routeid,proto3" json:"routeid,omitempty"`
	Routemap []*RouteStation `protobuf:"bytes,2,rep,name=routemap,proto3" json:"routemap,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetRouteid() int64 {
	if x != nil {
		return x.Routeid
	}
	return 0
}

func (x *Route) GetRoutemap() []*RouteStation {
	if x != nil {
		return x.Routemap
	}
	return nil
}

type AddRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routeid int64           `protobuf:"varint,1,opt,name=routeid,proto3" json:"routeid,omitempty"`
	Station []*RouteStation `protobuf:"bytes,2,rep,name=station,proto3" json:"station,omitempty"`
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{2}
}

func (x *AddRouteRequest) GetRouteid() int64 {
	if x != nil {
		return x.Routeid
	}
	return 0
}

func (x *AddRouteRequest) GetStation() []*RouteStation {
	if x != nil {
		return x.Station
	}
	return nil
}

type AddRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddRouteResponse) Reset() {
	*x = AddRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteResponse) ProtoMessage() {}

func (x *AddRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteResponse.ProtoReflect.Descriptor instead.
func (*AddRouteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{3}
}

func (x *AddRouteResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddRouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Add station
type AddStationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stationid   int64  `protobuf:"varint,1,opt,name=stationid,proto3" json:"stationid,omitempty"`
	Stationname string `protobuf:"bytes,2,opt,name=stationname,proto3" json:"stationname,omitempty"`
	City        string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *AddStationRequest) Reset() {
	*x = AddStationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStationRequest) ProtoMessage() {}

func (x *AddStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStationRequest.ProtoReflect.Descriptor instead.
func (*AddStationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{4}
}

func (x *AddStationRequest) GetStationid() int64 {
	if x != nil {
		return x.Stationid
	}
	return 0
}

func (x *AddStationRequest) GetStationname() string {
	if x != nil {
		return x.Stationname
	}
	return ""
}

func (x *AddStationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type AddStationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddStationResponse) Reset() {
	*x = AddStationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStationResponse) ProtoMessage() {}

func (x *AddStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStationResponse.ProtoReflect.Descriptor instead.
func (*AddStationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{5}
}

func (x *AddStationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddStationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Add train
type AddTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainnumber int64  `protobuf:"varint,1,opt,name=trainnumber,proto3" json:"trainnumber,omitempty"`
	Trainname   string `protobuf:"bytes,2,opt,name=trainname,proto3" json:"trainname,omitempty"`
}

func (x *AddTrainRequest) Reset() {
	*x = AddTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainRequest) ProtoMessage() {}

func (x *AddTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainRequest.ProtoReflect.Descriptor instead.
func (*AddTrainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{6}
}

func (x *AddTrainRequest) GetTrainnumber() int64 {
	if x != nil {
		return x.Trainnumber
	}
	return 0
}

func (x *AddTrainRequest) GetTrainname() string {
	if x != nil {
		return x.Trainname
	}
	return ""
}

type AddTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddTrainResponse) Reset() {
	*x = AddTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainResponse) ProtoMessage() {}

func (x *AddTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainResponse.ProtoReflect.Descriptor instead.
func (*AddTrainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{7}
}

func (x *AddTrainResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddTrainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Update route
type UpdateTrainRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainnumber int64  `protobuf:"varint,1,opt,name=trainnumber,proto3" json:"trainnumber,omitempty"`
	Route       *Route `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *UpdateTrainRouteRequest) Reset() {
	*x = UpdateTrainRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrainRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainRouteRequest) ProtoMessage() {}

func (x *UpdateTrainRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrainRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTrainRouteRequest) GetTrainnumber() int64 {
	if x != nil {
		return x.Trainnumber
	}
	return 0
}

func (x *UpdateTrainRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type UpdateTrainRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateTrainRouteResponse) Reset() {
	*x = UpdateTrainRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrainRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainRouteResponse) ProtoMessage() {}

func (x *UpdateTrainRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainRouteResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrainRouteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTrainRouteResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateTrainRouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_train_proto protoreflect.FileDescriptor

var file_pkg_pb_train_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x0c,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x22, 0x5a, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x67, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x22, 0x42, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x51, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5f, 0x0a, 0x17, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x48, 0x0a, 0x18, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xab, 0x02, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x41, 0x64, 0x64,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64,
	0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41,
	0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x1e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_train_proto_rawDescOnce sync.Once
	file_pkg_pb_train_proto_rawDescData = file_pkg_pb_train_proto_rawDesc
)

func file_pkg_pb_train_proto_rawDescGZIP() []byte {
	file_pkg_pb_train_proto_rawDescOnce.Do(func() {
		file_pkg_pb_train_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_train_proto_rawDescData)
	})
	return file_pkg_pb_train_proto_rawDescData
}

var file_pkg_pb_train_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_pb_train_proto_goTypes = []interface{}{
	(*RouteStation)(nil),             // 0: Train.RouteStation
	(*Route)(nil),                    // 1: Train.Route
	(*AddRouteRequest)(nil),          // 2: Train.AddRouteRequest
	(*AddRouteResponse)(nil),         // 3: Train.AddRouteResponse
	(*AddStationRequest)(nil),        // 4: Train.AddStationRequest
	(*AddStationResponse)(nil),       // 5: Train.AddStationResponse
	(*AddTrainRequest)(nil),          // 6: Train.AddTrainRequest
	(*AddTrainResponse)(nil),         // 7: Train.AddTrainResponse
	(*UpdateTrainRouteRequest)(nil),  // 8: Train.UpdateTrainRouteRequest
	(*UpdateTrainRouteResponse)(nil), // 9: Train.UpdateTrainRouteResponse
	(*timestamp.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_pkg_pb_train_proto_depIdxs = []int32{
	10, // 0: Train.RouteStation.time:type_name -> google.protobuf.Timestamp
	0,  // 1: Train.Route.routemap:type_name -> Train.RouteStation
	0,  // 2: Train.AddRouteRequest.station:type_name -> Train.RouteStation
	1,  // 3: Train.UpdateTrainRouteRequest.route:type_name -> Train.Route
	6,  // 4: Train.TrainManagement.AddTrain:input_type -> Train.AddTrainRequest
	4,  // 5: Train.TrainManagement.AddStation:input_type -> Train.AddStationRequest
	2,  // 6: Train.TrainManagement.AddRoute:input_type -> Train.AddRouteRequest
	8,  // 7: Train.TrainManagement.UpdateTrainRoute:input_type -> Train.UpdateTrainRouteRequest
	7,  // 8: Train.TrainManagement.AddTrain:output_type -> Train.AddTrainResponse
	5,  // 9: Train.TrainManagement.AddStation:output_type -> Train.AddStationResponse
	3,  // 10: Train.TrainManagement.AddRoute:output_type -> Train.AddRouteResponse
	9,  // 11: Train.TrainManagement.UpdateTrainRoute:output_type -> Train.UpdateTrainRouteResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_pb_train_proto_init() }
func file_pkg_pb_train_proto_init() {
	if File_pkg_pb_train_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_train_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteStation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrainRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrainRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_train_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_train_proto_goTypes,
		DependencyIndexes: file_pkg_pb_train_proto_depIdxs,
		MessageInfos:      file_pkg_pb_train_proto_msgTypes,
	}.Build()
	File_pkg_pb_train_proto = out.File
	file_pkg_pb_train_proto_rawDesc = nil
	file_pkg_pb_train_proto_goTypes = nil
	file_pkg_pb_train_proto_depIdxs = nil
}
