// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: pkg/pb/train.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewCompartmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewCompartmentRequest) Reset() {
	*x = ViewCompartmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCompartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCompartmentRequest) ProtoMessage() {}

func (x *ViewCompartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCompartmentRequest.ProtoReflect.Descriptor instead.
func (*ViewCompartmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{0}
}

type ViewCompartmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Compartment []*CompartmentDetails `protobuf:"bytes,1,rep,name=compartment,proto3" json:"compartment,omitempty"`
}

func (x *ViewCompartmentResponse) Reset() {
	*x = ViewCompartmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCompartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCompartmentResponse) ProtoMessage() {}

func (x *ViewCompartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCompartmentResponse.ProtoReflect.Descriptor instead.
func (*ViewCompartmentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{1}
}

func (x *ViewCompartmentResponse) GetCompartment() []*CompartmentDetails {
	if x != nil {
		return x.Compartment
	}
	return nil
}

type CompartmentDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompartmentId   string `protobuf:"bytes,1,opt,name=compartmentId,proto3" json:"compartmentId,omitempty"`
	CompartmentType string `protobuf:"bytes,2,opt,name=compartmentType,proto3" json:"compartmentType,omitempty"`
	Price           int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CompartmentDetails) Reset() {
	*x = CompartmentDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompartmentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompartmentDetails) ProtoMessage() {}

func (x *CompartmentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompartmentDetails.ProtoReflect.Descriptor instead.
func (*CompartmentDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{2}
}

func (x *CompartmentDetails) GetCompartmentId() string {
	if x != nil {
		return x.CompartmentId
	}
	return ""
}

func (x *CompartmentDetails) GetCompartmentType() string {
	if x != nil {
		return x.CompartmentType
	}
	return ""
}

func (x *CompartmentDetails) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ViewRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewRoutesRequest) Reset() {
	*x = ViewRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRoutesRequest) ProtoMessage() {}

func (x *ViewRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRoutesRequest.ProtoReflect.Descriptor instead.
func (*ViewRoutesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{3}
}

type ViewRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteDetails []*RouteDetails `protobuf:"bytes,1,rep,name=RouteDetails,proto3" json:"RouteDetails,omitempty"`
}

func (x *ViewRoutesResponse) Reset() {
	*x = ViewRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRoutesResponse) ProtoMessage() {}

func (x *ViewRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRoutesResponse.ProtoReflect.Descriptor instead.
func (*ViewRoutesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{4}
}

func (x *ViewRoutesResponse) GetRouteDetails() []*RouteDetails {
	if x != nil {
		return x.RouteDetails
	}
	return nil
}

type RouteDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteName string `protobuf:"bytes,1,opt,name=routeName,proto3" json:"routeName,omitempty"`
	RouteId   string `protobuf:"bytes,2,opt,name=routeId,proto3" json:"routeId,omitempty"`
}

func (x *RouteDetails) Reset() {
	*x = RouteDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDetails) ProtoMessage() {}

func (x *RouteDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDetails.ProtoReflect.Descriptor instead.
func (*RouteDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{5}
}

func (x *RouteDetails) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *RouteDetails) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

//search train by name
type SearchTrainByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainName string `protobuf:"bytes,1,opt,name=trainName,proto3" json:"trainName,omitempty"`
}

func (x *SearchTrainByNameRequest) Reset() {
	*x = SearchTrainByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTrainByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrainByNameRequest) ProtoMessage() {}

func (x *SearchTrainByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrainByNameRequest.ProtoReflect.Descriptor instead.
func (*SearchTrainByNameRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{6}
}

func (x *SearchTrainByNameRequest) GetTrainName() string {
	if x != nil {
		return x.TrainName
	}
	return ""
}

type SearchTrainByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainName    string `protobuf:"bytes,1,opt,name=trainName,proto3" json:"trainName,omitempty"`
	TrainType    string `protobuf:"bytes,2,opt,name=trainType,proto3" json:"trainType,omitempty"`
	TranNumber   string `protobuf:"bytes,3,opt,name=tranNumber,proto3" json:"tranNumber,omitempty"`
	Startingtime string `protobuf:"bytes,4,opt,name=startingtime,proto3" json:"startingtime,omitempty"`
	Endingtime   string `protobuf:"bytes,5,opt,name=endingtime,proto3" json:"endingtime,omitempty"`
}

func (x *SearchTrainByNameResponse) Reset() {
	*x = SearchTrainByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTrainByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrainByNameResponse) ProtoMessage() {}

func (x *SearchTrainByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrainByNameResponse.ProtoReflect.Descriptor instead.
func (*SearchTrainByNameResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{7}
}

func (x *SearchTrainByNameResponse) GetTrainName() string {
	if x != nil {
		return x.TrainName
	}
	return ""
}

func (x *SearchTrainByNameResponse) GetTrainType() string {
	if x != nil {
		return x.TrainType
	}
	return ""
}

func (x *SearchTrainByNameResponse) GetTranNumber() string {
	if x != nil {
		return x.TranNumber
	}
	return ""
}

func (x *SearchTrainByNameResponse) GetStartingtime() string {
	if x != nil {
		return x.Startingtime
	}
	return ""
}

func (x *SearchTrainByNameResponse) GetEndingtime() string {
	if x != nil {
		return x.Endingtime
	}
	return ""
}

//View station
type ViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewRequest) Reset() {
	*x = ViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRequest) ProtoMessage() {}

func (x *ViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRequest.ProtoReflect.Descriptor instead.
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{8}
}

type ViewStationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Stations []*Station `protobuf:"bytes,3,rep,name=stations,proto3" json:"stations,omitempty"`
}

func (x *ViewStationResponse) Reset() {
	*x = ViewStationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStationResponse) ProtoMessage() {}

func (x *ViewStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStationResponse.ProtoReflect.Descriptor instead.
func (*ViewStationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{9}
}

func (x *ViewStationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ViewStationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ViewStationResponse) GetStations() []*Station {
	if x != nil {
		return x.Stations
	}
	return nil
}

type Station struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stationid   string `protobuf:"bytes,1,opt,name=stationid,proto3" json:"stationid,omitempty"`
	StationName string `protobuf:"bytes,2,opt,name=StationName,proto3" json:"StationName,omitempty"`
	City        string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *Station) Reset() {
	*x = Station{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Station) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station) ProtoMessage() {}

func (x *Station) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station.ProtoReflect.Descriptor instead.
func (*Station) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{10}
}

func (x *Station) GetStationid() string {
	if x != nil {
		return x.Stationid
	}
	return ""
}

func (x *Station) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *Station) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

//update seat into train
type Compartment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seatid string `protobuf:"bytes,1,opt,name=seatid,proto3" json:"seatid,omitempty"`
}

func (x *Compartment) Reset() {
	*x = Compartment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Compartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compartment) ProtoMessage() {}

func (x *Compartment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compartment.ProtoReflect.Descriptor instead.
func (*Compartment) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{11}
}

func (x *Compartment) GetSeatid() string {
	if x != nil {
		return x.Seatid
	}
	return ""
}

type UpdateSeatIntoTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainnumber  int64          `protobuf:"varint,1,opt,name=trainnumber,proto3" json:"trainnumber,omitempty"`
	Compartments []*Compartment `protobuf:"bytes,2,rep,name=compartments,proto3" json:"compartments,omitempty"`
}

func (x *UpdateSeatIntoTrainRequest) Reset() {
	*x = UpdateSeatIntoTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeatIntoTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatIntoTrainRequest) ProtoMessage() {}

func (x *UpdateSeatIntoTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatIntoTrainRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeatIntoTrainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSeatIntoTrainRequest) GetTrainnumber() int64 {
	if x != nil {
		return x.Trainnumber
	}
	return 0
}

func (x *UpdateSeatIntoTrainRequest) GetCompartments() []*Compartment {
	if x != nil {
		return x.Compartments
	}
	return nil
}

type UpdateSeatIntoTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateSeatIntoTrainResponse) Reset() {
	*x = UpdateSeatIntoTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeatIntoTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeatIntoTrainResponse) ProtoMessage() {}

func (x *UpdateSeatIntoTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeatIntoTrainResponse.ProtoReflect.Descriptor instead.
func (*UpdateSeatIntoTrainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSeatIntoTrainResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateSeatIntoTrainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//Adding seat
type AddSeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price        int64  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Numberofseat int64  `protobuf:"varint,2,opt,name=numberofseat,proto3" json:"numberofseat,omitempty"`
	Typeofseat   string `protobuf:"bytes,3,opt,name=typeofseat,proto3" json:"typeofseat,omitempty"`
	Compartment  string `protobuf:"bytes,4,opt,name=compartment,proto3" json:"compartment,omitempty"`
}

func (x *AddSeatRequest) Reset() {
	*x = AddSeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSeatRequest) ProtoMessage() {}

func (x *AddSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSeatRequest.ProtoReflect.Descriptor instead.
func (*AddSeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{14}
}

func (x *AddSeatRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddSeatRequest) GetNumberofseat() int64 {
	if x != nil {
		return x.Numberofseat
	}
	return 0
}

func (x *AddSeatRequest) GetTypeofseat() string {
	if x != nil {
		return x.Typeofseat
	}
	return ""
}

func (x *AddSeatRequest) GetCompartment() string {
	if x != nil {
		return x.Compartment
	}
	return ""
}

type AddSeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddSeatResponse) Reset() {
	*x = AddSeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSeatResponse) ProtoMessage() {}

func (x *AddSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSeatResponse.ProtoReflect.Descriptor instead.
func (*AddSeatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{15}
}

func (x *AddSeatResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddSeatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//viewTrain
type ViewTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewTrainRequest) Reset() {
	*x = ViewTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewTrainRequest) ProtoMessage() {}

func (x *ViewTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewTrainRequest.ProtoReflect.Descriptor instead.
func (*ViewTrainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{16}
}

type ViewTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error     string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Traindata []*Train `protobuf:"bytes,3,rep,name=traindata,proto3" json:"traindata,omitempty"`
}

func (x *ViewTrainResponse) Reset() {
	*x = ViewTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewTrainResponse) ProtoMessage() {}

func (x *ViewTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewTrainResponse.ProtoReflect.Descriptor instead.
func (*ViewTrainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{17}
}

func (x *ViewTrainResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ViewTrainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ViewTrainResponse) GetTraindata() []*Train {
	if x != nil {
		return x.Traindata
	}
	return nil
}

type Train struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainname   string `protobuf:"bytes,1,opt,name=trainname,proto3" json:"trainname,omitempty"`
	Trainnumber int64  `protobuf:"varint,2,opt,name=trainnumber,proto3" json:"trainnumber,omitempty"`
}

func (x *Train) Reset() {
	*x = Train{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Train.ProtoReflect.Descriptor instead.
func (*Train) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{18}
}

func (x *Train) GetTrainname() string {
	if x != nil {
		return x.Trainname
	}
	return ""
}

func (x *Train) GetTrainnumber() int64 {
	if x != nil {
		return x.Trainnumber
	}
	return 0
}

//Add station
type AddStationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stationname string `protobuf:"bytes,1,opt,name=stationname,proto3" json:"stationname,omitempty"`
	City        string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *AddStationRequest) Reset() {
	*x = AddStationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStationRequest) ProtoMessage() {}

func (x *AddStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStationRequest.ProtoReflect.Descriptor instead.
func (*AddStationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{19}
}

func (x *AddStationRequest) GetStationname() string {
	if x != nil {
		return x.Stationname
	}
	return ""
}

func (x *AddStationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type AddStationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddStationResponse) Reset() {
	*x = AddStationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStationResponse) ProtoMessage() {}

func (x *AddStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStationResponse.ProtoReflect.Descriptor instead.
func (*AddStationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{20}
}

func (x *AddStationResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddStationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//Add train
type AddTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainnumber  int64   `protobuf:"varint,1,opt,name=trainnumber,proto3" json:"trainnumber,omitempty"`
	Trainname    string  `protobuf:"bytes,2,opt,name=trainname,proto3" json:"trainname,omitempty"`
	Startingtime string  `protobuf:"bytes,3,opt,name=startingtime,proto3" json:"startingtime,omitempty"`
	Endingtime   string  `protobuf:"bytes,4,opt,name=endingtime,proto3" json:"endingtime,omitempty"`
	Traintype    string  `protobuf:"bytes,5,opt,name=traintype,proto3" json:"traintype,omitempty"`
	Date         []*Date `protobuf:"bytes,6,rep,name=Date,proto3" json:"Date,omitempty"`
}

func (x *AddTrainRequest) Reset() {
	*x = AddTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainRequest) ProtoMessage() {}

func (x *AddTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainRequest.ProtoReflect.Descriptor instead.
func (*AddTrainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{21}
}

func (x *AddTrainRequest) GetTrainnumber() int64 {
	if x != nil {
		return x.Trainnumber
	}
	return 0
}

func (x *AddTrainRequest) GetTrainname() string {
	if x != nil {
		return x.Trainname
	}
	return ""
}

func (x *AddTrainRequest) GetStartingtime() string {
	if x != nil {
		return x.Startingtime
	}
	return ""
}

func (x *AddTrainRequest) GetEndingtime() string {
	if x != nil {
		return x.Endingtime
	}
	return ""
}

func (x *AddTrainRequest) GetTraintype() string {
	if x != nil {
		return x.Traintype
	}
	return ""
}

func (x *AddTrainRequest) GetDate() []*Date {
	if x != nil {
		return x.Date
	}
	return nil
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{22}
}

func (x *Date) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type AddTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddTrainResponse) Reset() {
	*x = AddTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainResponse) ProtoMessage() {}

func (x *AddTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainResponse.ProtoReflect.Descriptor instead.
func (*AddTrainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{23}
}

func (x *AddTrainResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddTrainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Add route
type RouteStation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stationid string               `protobuf:"bytes,1,opt,name=stationid,proto3" json:"stationid,omitempty"`
	Distance  float32              `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Time      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *RouteStation) Reset() {
	*x = RouteStation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteStation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStation) ProtoMessage() {}

func (x *RouteStation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStation.ProtoReflect.Descriptor instead.
func (*RouteStation) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{24}
}

func (x *RouteStation) GetStationid() string {
	if x != nil {
		return x.Stationid
	}
	return ""
}

func (x *RouteStation) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RouteStation) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routeid   string          `protobuf:"bytes,1,opt,name=routeid,proto3" json:"routeid,omitempty"`
	Routename string          `protobuf:"bytes,2,opt,name=routename,proto3" json:"routename,omitempty"`
	Routemap  []*RouteStation `protobuf:"bytes,3,rep,name=routemap,proto3" json:"routemap,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{25}
}

func (x *Route) GetRouteid() string {
	if x != nil {
		return x.Routeid
	}
	return ""
}

func (x *Route) GetRoutename() string {
	if x != nil {
		return x.Routename
	}
	return ""
}

func (x *Route) GetRoutemap() []*RouteStation {
	if x != nil {
		return x.Routemap
	}
	return nil
}

type AddRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{26}
}

func (x *AddRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type AddRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddRouteResponse) Reset() {
	*x = AddRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteResponse) ProtoMessage() {}

func (x *AddRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteResponse.ProtoReflect.Descriptor instead.
func (*AddRouteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{27}
}

func (x *AddRouteResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddRouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//Updata train routeroutemap
type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainnumber int64  `protobuf:"varint,1,opt,name=trainnumber,proto3" json:"trainnumber,omitempty"`
	Route       string `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateRequest) GetTrainnumber() int64 {
	if x != nil {
		return x.Trainnumber
	}
	return 0
}

func (x *UpdateRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

//Search train
type SearchTrainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date                 string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Sourcestationid      string `protobuf:"bytes,2,opt,name=sourcestationid,proto3" json:"sourcestationid,omitempty"`
	Destinationstationid string `protobuf:"bytes,3,opt,name=destinationstationid,proto3" json:"destinationstationid,omitempty"`
}

func (x *SearchTrainRequest) Reset() {
	*x = SearchTrainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrainRequest) ProtoMessage() {}

func (x *SearchTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrainRequest.ProtoReflect.Descriptor instead.
func (*SearchTrainRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{30}
}

func (x *SearchTrainRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SearchTrainRequest) GetSourcestationid() string {
	if x != nil {
		return x.Sourcestationid
	}
	return ""
}

func (x *SearchTrainRequest) GetDestinationstationid() string {
	if x != nil {
		return x.Destinationstationid
	}
	return ""
}

type SearchTrainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int64        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error     string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Traindata []*TrainData `protobuf:"bytes,3,rep,name=traindata,proto3" json:"traindata,omitempty"`
}

func (x *SearchTrainResponse) Reset() {
	*x = SearchTrainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTrainResponse) ProtoMessage() {}

func (x *SearchTrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTrainResponse.ProtoReflect.Descriptor instead.
func (*SearchTrainResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{31}
}

func (x *SearchTrainResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SearchTrainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchTrainResponse) GetTraindata() []*TrainData {
	if x != nil {
		return x.Traindata
	}
	return nil
}

type TrainData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trainname string               `protobuf:"bytes,1,opt,name=trainname,proto3" json:"trainname,omitempty"`
	Time      *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TrainData) Reset() {
	*x = TrainData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_train_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainData) ProtoMessage() {}

func (x *TrainData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_train_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainData.ProtoReflect.Descriptor instead.
func (*TrainData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_train_proto_rawDescGZIP(), []int{32}
}

func (x *TrainData) GetTrainname() string {
	if x != nil {
		return x.Trainname
	}
	return ""
}

func (x *TrainData) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_pkg_pb_train_proto protoreflect.FileDescriptor

var file_pkg_pb_train_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16,
	0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x17, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x7a,
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x56, 0x69,
	0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4d, 0x0a, 0x12, 0x56, 0x69, 0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x46,
	0x0a, 0x0c, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0xbb, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72,
	0x61, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x72, 0x61, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x0d,
	0x0a, 0x0b, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6f, 0x0a,
	0x13, 0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5d,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x25, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x74, 0x69, 0x64, 0x22, 0x76, 0x0a, 0x1a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x61, 0x74, 0x49, 0x6e, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x1b,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x6f, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8c, 0x01, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6f, 0x66, 0x73, 0x65,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x6f, 0x66, 0x73, 0x65, 0x61, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x6f, 0x66,
	0x73, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x79, 0x70, 0x65,
	0x6f, 0x66, 0x73, 0x65, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x56, 0x69, 0x65,
	0x77, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6d, 0x0a,
	0x11, 0x56, 0x69, 0x65, 0x77, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x2a, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x22, 0x47, 0x0a, 0x05,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x42, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0xd4, 0x01, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x18, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x78, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x70, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x6d, 0x61, 0x70, 0x22, 0x35, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x40, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x14, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x22, 0x73,
	0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x59, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0xf0,
	0x06, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x16,
	0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x19, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x09, 0x56, 0x69, 0x65, 0x77, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x17, 0x2e,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53, 0x65, 0x61, 0x74, 0x12, 0x15, 0x2e,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64,
	0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x6f,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x21, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x6f, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74, 0x6f, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x0b, 0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x2e,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x58, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x56, 0x69, 0x65,
	0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x0f, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_train_proto_rawDescOnce sync.Once
	file_pkg_pb_train_proto_rawDescData = file_pkg_pb_train_proto_rawDesc
)

func file_pkg_pb_train_proto_rawDescGZIP() []byte {
	file_pkg_pb_train_proto_rawDescOnce.Do(func() {
		file_pkg_pb_train_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_train_proto_rawDescData)
	})
	return file_pkg_pb_train_proto_rawDescData
}

var file_pkg_pb_train_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_pkg_pb_train_proto_goTypes = []interface{}{
	(*ViewCompartmentRequest)(nil),      // 0: Train.ViewCompartmentRequest
	(*ViewCompartmentResponse)(nil),     // 1: Train.ViewCompartmentResponse
	(*CompartmentDetails)(nil),          // 2: Train.compartmentDetails
	(*ViewRoutesRequest)(nil),           // 3: Train.ViewRoutesRequest
	(*ViewRoutesResponse)(nil),          // 4: Train.ViewRoutesResponse
	(*RouteDetails)(nil),                // 5: Train.routeDetails
	(*SearchTrainByNameRequest)(nil),    // 6: Train.SearchTrainByNameRequest
	(*SearchTrainByNameResponse)(nil),   // 7: Train.SearchTrainByNameResponse
	(*ViewRequest)(nil),                 // 8: Train.ViewRequest
	(*ViewStationResponse)(nil),         // 9: Train.ViewStationResponse
	(*Station)(nil),                     // 10: Train.station
	(*Compartment)(nil),                 // 11: Train.Compartment
	(*UpdateSeatIntoTrainRequest)(nil),  // 12: Train.updateSeatIntoTrainRequest
	(*UpdateSeatIntoTrainResponse)(nil), // 13: Train.updateSeatIntoTrainResponse
	(*AddSeatRequest)(nil),              // 14: Train.AddSeatRequest
	(*AddSeatResponse)(nil),             // 15: Train.AddSeatResponse
	(*ViewTrainRequest)(nil),            // 16: Train.ViewTrainRequest
	(*ViewTrainResponse)(nil),           // 17: Train.ViewTrainResponse
	(*Train)(nil),                       // 18: Train.Train
	(*AddStationRequest)(nil),           // 19: Train.AddStationRequest
	(*AddStationResponse)(nil),          // 20: Train.AddStationResponse
	(*AddTrainRequest)(nil),             // 21: Train.AddTrainRequest
	(*Date)(nil),                        // 22: Train.date
	(*AddTrainResponse)(nil),            // 23: Train.AddTrainResponse
	(*RouteStation)(nil),                // 24: Train.RouteStation
	(*Route)(nil),                       // 25: Train.Route
	(*AddRouteRequest)(nil),             // 26: Train.AddRouteRequest
	(*AddRouteResponse)(nil),            // 27: Train.AddRouteResponse
	(*UpdateRequest)(nil),               // 28: Train.UpdateRequest
	(*UpdateResponse)(nil),              // 29: Train.UpdateResponse
	(*SearchTrainRequest)(nil),          // 30: Train.SearchTrainRequest
	(*SearchTrainResponse)(nil),         // 31: Train.SearchTrainResponse
	(*TrainData)(nil),                   // 32: Train.TrainData
	(*timestamp.Timestamp)(nil),         // 33: google.protobuf.Timestamp
}
var file_pkg_pb_train_proto_depIdxs = []int32{
	2,  // 0: Train.ViewCompartmentResponse.compartment:type_name -> Train.compartmentDetails
	5,  // 1: Train.ViewRoutesResponse.RouteDetails:type_name -> Train.routeDetails
	10, // 2: Train.ViewStationResponse.stations:type_name -> Train.station
	11, // 3: Train.updateSeatIntoTrainRequest.compartments:type_name -> Train.Compartment
	18, // 4: Train.ViewTrainResponse.traindata:type_name -> Train.Train
	22, // 5: Train.AddTrainRequest.Date:type_name -> Train.date
	33, // 6: Train.RouteStation.time:type_name -> google.protobuf.Timestamp
	24, // 7: Train.Route.routemap:type_name -> Train.RouteStation
	25, // 8: Train.AddRouteRequest.route:type_name -> Train.Route
	32, // 9: Train.SearchTrainResponse.traindata:type_name -> Train.TrainData
	33, // 10: Train.TrainData.time:type_name -> google.protobuf.Timestamp
	21, // 11: Train.TrainManagement.AddTrain:input_type -> Train.AddTrainRequest
	19, // 12: Train.TrainManagement.AddStation:input_type -> Train.AddStationRequest
	26, // 13: Train.TrainManagement.AddRoute:input_type -> Train.AddRouteRequest
	28, // 14: Train.TrainManagement.UpdateTrainRoute:input_type -> Train.UpdateRequest
	30, // 15: Train.TrainManagement.SearchTrain:input_type -> Train.SearchTrainRequest
	16, // 16: Train.TrainManagement.ViewTrain:input_type -> Train.ViewTrainRequest
	14, // 17: Train.TrainManagement.AddSeat:input_type -> Train.AddSeatRequest
	12, // 18: Train.TrainManagement.UpdateSeatIntoTrain:input_type -> Train.updateSeatIntoTrainRequest
	8,  // 19: Train.TrainManagement.ViewStation:input_type -> Train.ViewRequest
	6,  // 20: Train.TrainManagement.SearchTrainByName:input_type -> Train.SearchTrainByNameRequest
	3,  // 21: Train.TrainManagement.ViewRoute:input_type -> Train.ViewRoutesRequest
	0,  // 22: Train.TrainManagement.ViewCompartment:input_type -> Train.ViewCompartmentRequest
	23, // 23: Train.TrainManagement.AddTrain:output_type -> Train.AddTrainResponse
	20, // 24: Train.TrainManagement.AddStation:output_type -> Train.AddStationResponse
	27, // 25: Train.TrainManagement.AddRoute:output_type -> Train.AddRouteResponse
	29, // 26: Train.TrainManagement.UpdateTrainRoute:output_type -> Train.UpdateResponse
	31, // 27: Train.TrainManagement.SearchTrain:output_type -> Train.SearchTrainResponse
	17, // 28: Train.TrainManagement.ViewTrain:output_type -> Train.ViewTrainResponse
	15, // 29: Train.TrainManagement.AddSeat:output_type -> Train.AddSeatResponse
	13, // 30: Train.TrainManagement.UpdateSeatIntoTrain:output_type -> Train.updateSeatIntoTrainResponse
	9,  // 31: Train.TrainManagement.ViewStation:output_type -> Train.ViewStationResponse
	7,  // 32: Train.TrainManagement.SearchTrainByName:output_type -> Train.SearchTrainByNameResponse
	4,  // 33: Train.TrainManagement.ViewRoute:output_type -> Train.ViewRoutesResponse
	1,  // 34: Train.TrainManagement.ViewCompartment:output_type -> Train.ViewCompartmentResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_pb_train_proto_init() }
func file_pkg_pb_train_proto_init() {
	if File_pkg_pb_train_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_train_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCompartmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCompartmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompartmentDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTrainByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTrainByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewStationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Station); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Compartment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeatIntoTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeatIntoTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Train); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteStation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTrainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTrainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_train_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_train_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_train_proto_goTypes,
		DependencyIndexes: file_pkg_pb_train_proto_depIdxs,
		MessageInfos:      file_pkg_pb_train_proto_msgTypes,
	}.Build()
	File_pkg_pb_train_proto = out.File
	file_pkg_pb_train_proto_rawDesc = nil
	file_pkg_pb_train_proto_goTypes = nil
	file_pkg_pb_train_proto_depIdxs = nil
}
